using System.Globalization;
using System.Text;
using DIR.Lib;

// Bakes glyphs into rectangle runs the app draws with plain FillRect. See BakeIcons.csproj for why.
//
// Usage: dotnet run --project tools/BakeIcons -- <font.ttf> <output.g.cs>

if (args.Length < 2)
{
    Console.Error.WriteLine("usage: BakeIcons <source-font> <output-file>");
    return 2;
}

var fontPath = args[0];
var outputPath = args[1];

if (!File.Exists(fontPath))
{
    Console.Error.WriteLine($"BakeIcons: source font not found: {fontPath}");
    return 2;
}

// The manifest. Deliberately a literal here rather than a data file: it is three lines, it changes
// about never, and a separate manifest format would be more machinery than the thing it describes.
//
// LICENSING: the source font must be one whose licence permits redistributing glyph shapes, because
// that is exactly what baking does. Noto is OFL. Do NOT point this at a proprietary system face --
// C:\Windows\Fonts\seguiemj.ttf is Microsoft's, and the fact that the RUNTIME emoji probe legitimately
// falls back to it does not make its outlines ours to commit.
(string Name, int Codepoint, string Meaning)[] icons =
[
    ("Spiral", 0x1F300, "deep-sky object overlays"),
];

// The sizes the toolbar actually asks for: BaseToolbarMarkSize (13) times the DPI scales in use.
// Baked per size rather than scaled from one master, because a run is a row of pixels -- scaling the
// rows either overlaps them or leaves gaps, and both show at this size.
int[] sizes = [13, 16, 20, 26, 39];

// Alpha levels. One bit would be chunky against the antialiased text beside it; four levels is enough
// to keep an edge readable and costs only a few more runs.
const int AlphaLevels = 4;

using var rasterizer = new ManagedFontRasterizer();
var sb = new StringBuilder();

sb.AppendLine("// <auto-generated>");
sb.AppendLine("//     Generated by tools/BakeIcons. Do not edit by hand -- re-run the tool and commit.");
sb.AppendLine($"//     Source font: {Path.GetFileName(fontPath)}");
sb.AppendLine("// </auto-generated>");
sb.AppendLine("#nullable enable");
sb.AppendLine();
sb.AppendLine("using System;");
sb.AppendLine("using System.Collections.Immutable;");
sb.AppendLine();
sb.AppendLine("namespace TianWen.UI.Abstractions");
sb.AppendLine("{");
sb.AppendLine("    /// <summary>");
sb.AppendLine("    /// Glyphs baked to rectangle runs at build-host time, so an icon needs no font at runtime.");
sb.AppendLine("    /// </summary>");
sb.AppendLine("    /// <remarks>");
sb.AppendLine("    /// <para>Three things this buys over drawing the glyph from an installed face, each of which the");
sb.AppendLine("    /// font path actually cost: it works where no emoji face exists (a Linux host resolved none, so");
sb.AppendLine("    /// every emoji mark silently drew NOTHING); it is monochrome, so a mark tints and dims with the");
sb.AppendLine("    /// label beside it, which a COLRv1 glyph carrying its own palette cannot; and it is identical on");
sb.AppendLine("    /// every machine, where the runtime path varied with whichever face the host resolved.</para>");
sb.AppendLine("    /// <para>A run is one horizontal span of constant alpha, so drawing is a loop of FillRect and");
sb.AppendLine("    /// needs no new member on the renderer seam -- the same reason DIR.Lib's own IconKind painter is");
sb.AppendLine("    /// built from rectangles.</para>");
sb.AppendLine("    /// </remarks>");
sb.AppendLine("    internal static class BakedIcons");
sb.AppendLine("    {");
sb.AppendLine("        /// <summary>One horizontal span of constant coverage, in mask pixels.</summary>");
sb.AppendLine("        internal readonly record struct Run(byte X, byte Y, byte Width, byte Alpha);");
sb.AppendLine();
sb.AppendLine("        /// <summary>One baked size of one icon.</summary>");
sb.AppendLine("        internal readonly record struct Mask(int Size, ImmutableArray<Run> Runs);");
sb.AppendLine();

var totalRuns = 0;

foreach (var (name, codepoint, meaning) in icons)
{
    var rune = new System.Text.Rune(codepoint);
    var masks = new List<(int Size, List<(int X, int Y, int W, int A)> Runs)>();

    foreach (var size in sizes)
    {
        var bmp = rasterizer.RasterizeGlyph(fontPath, size, rune);
        if (bmp.Width <= 0 || bmp.Height <= 0 || bmp.Rgba.Length == 0)
        {
            Console.Error.WriteLine(
                $"BakeIcons: {name} (U+{codepoint:X4}) did not rasterise at {size}px from " +
                $"{Path.GetFileName(fontPath)} -- the face may not cover it.");
            return 1;
        }

        // Centre the glyph in a square mask of the requested size. The rasteriser returns the ink box
        // plus bearings; the mark is drawn into a square, so centring the INK is what makes a row of
        // different marks look aligned (bearing-relative placement puts each one wherever its own font
        // metrics say, which is right for text and wrong for an icon).
        var runs = new List<(int X, int Y, int W, int A)>();
        var offX = (size - bmp.Width) / 2;
        var offY = (size - bmp.Height) / 2;

        for (var row = 0; row < bmp.Height; row++)
        {
            var y = offY + row;
            if (y < 0 || y >= size)
            {
                continue;
            }

            var runStart = -1;
            var runLevel = 0;

            for (var col = 0; col <= bmp.Width; col++)
            {
                var level = 0;
                var x = offX + col;
                if (col < bmp.Width && x >= 0 && x < size)
                {
                    // Alpha is the coverage regardless of whether the face is colour or outline: a
                    // COLRv1 emoji rasterises its paint tree into RGBA, and the shape we want is its
                    // silhouette, which is exactly the alpha channel.
                    var alpha = bmp.Rgba[(row * bmp.Width + col) * 4 + 3];
                    level = alpha * AlphaLevels / 256;
                }

                if (level != runLevel)
                {
                    if (runLevel > 0 && runStart >= 0)
                    {
                        // Quantised level back to an 8-bit alpha. The TOP bucket must map to 255: an
                        // interior pixel is fully covered, and a bucket-centre mapping put it at 223,
                        // which made the whole mark read visibly greyer than the text and the other
                        // marks beside it. Saturating the top bucket costs nothing at the edges.
                        var a = Math.Min(255, (runLevel + 1) * 255 / AlphaLevels);
                        runs.Add((runStart, y, offX + col - runStart, a));
                    }
                    runStart = offX + col;
                    runLevel = level;
                }
            }
        }

        masks.Add((size, runs));
        totalRuns += runs.Count;
    }

    sb.AppendLine($"        /// <summary>U+{codepoint:X4} -- {meaning}.</summary>");
    sb.AppendLine($"        internal static readonly ImmutableArray<Mask> {name} =");
    sb.AppendLine("        [");
    foreach (var (size, runs) in masks)
    {
        sb.Append(CultureInfo.InvariantCulture, $"            new Mask({size}, [");
        for (var i = 0; i < runs.Count; i++)
        {
            var (x, y, w, a) = runs[i];
            sb.Append(CultureInfo.InvariantCulture, $"new({x},{y},{w},{a})");
            if (i < runs.Count - 1)
            {
                sb.Append(", ");
            }
        }
        sb.AppendLine("]),");
    }
    sb.AppendLine("        ];");
    sb.AppendLine();

    Console.WriteLine($"BakeIcons: {name} U+{codepoint:X4} -> {masks.Count} sizes, " +
        string.Join(", ", masks.Select(m => $"{m.Size}px:{m.Runs.Count}")));
}

sb.AppendLine("        /// <summary>The baked size nearest <paramref name=\"pixels\"/>.</summary>");
sb.AppendLine("        /// <remarks>");
sb.AppendLine("        /// Nearest rather than exact: DpiScale is continuous, so an exact match would need a bake per");
sb.AppendLine("        /// possible scale. Rows are drawn at the mask's own resolution and scaled by the caller, which");
sb.AppendLine("        /// is why picking the CLOSEST size matters -- a distant one scales visibly.");
sb.AppendLine("        /// </remarks>");
sb.AppendLine("        internal static Mask NearestSize(ImmutableArray<Mask> masks, float pixels)");
sb.AppendLine("        {");
sb.AppendLine("            var best = masks[0];");
sb.AppendLine("            var bestDelta = MathF.Abs(best.Size - pixels);");
sb.AppendLine("            foreach (var mask in masks)");
sb.AppendLine("            {");
sb.AppendLine("                var delta = MathF.Abs(mask.Size - pixels);");
sb.AppendLine("                if (delta < bestDelta)");
sb.AppendLine("                {");
sb.AppendLine("                    best = mask;");
sb.AppendLine("                    bestDelta = delta;");
sb.AppendLine("                }");
sb.AppendLine("            }");
sb.AppendLine("            return best;");
sb.AppendLine("        }");
sb.AppendLine("    }");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);
File.WriteAllText(outputPath, sb.ToString().ReplaceLineEndings("\r\n"));

Console.WriteLine($"BakeIcons: wrote {outputPath} ({totalRuns} runs total)");
return 0;
