using System.Globalization;
using System.Text;
using DIR.Lib;

// A thin wrapper over DIR.Lib's IconBaker: it owns the baking, this owns the file format. Everything
// about WHICH glyphs is an argument, so nothing app-specific lives here and the tool can serve a second
// consumer -- it is meant to be packed and run via `dnx`, the way SdlVulkan.Renderer.Inspector already is.
//
//   bake-icons --font <path> --out <file.g.cs> --namespace <ns>
//              --glyph Name=U+1F300 [--glyph ...]
//              [--class BakedIcons] [--sizes 13,16,20] [--levels 4] [--access internal]
//
// Emits DATA ONLY, typed as DIR.Lib.IconBaker.CoverageMask. An earlier version re-emitted the run/mask
// types and the size picker into every generated file, which is a copy of a library type per consumer.
//
// Hand-rolled argument parsing so the tool's only dependency is the rasteriser and it can be packed
// without dragging a CLI framework along.

var fontPath = "";
var outputPath = "";
var ns = "";
var className = "BakedIcons";
var access = "internal";
// The size ladder is DPI SCALES, not round numbers: a mark is BaseToolbarMarkSize (13 design units)
// times the scale, so these are 13 at 1.0, 1.25, 1.5, 1.75, 2.0, 2.5 and 3.0. Chosen that way because
// the caller scales the nearest bake, and a ladder of pretty numbers leaves gaps exactly where common
// hosts sit -- 13/16/20/26/39 forced 1.75x to resample by 14% and 2.5x by 25%, while this keeps every
// common scale within about 2%. Each extra size is ~200 runs, so closing the gaps is nearly free.
int[] sizes = [13, 16, 20, 23, 26, 33, 39];
var levels = IconBaker.DefaultAlphaLevels;
var icons = new List<(string Name, int Codepoint)>();

for (var i = 0; i < args.Length; i++)
{
    var next = i + 1 < args.Length ? args[i + 1] : null;
    switch (args[i])
    {
        case "--font" when next is not null: fontPath = next; i++; break;
        case "--out" when next is not null: outputPath = next; i++; break;
        case "--namespace" when next is not null: ns = next; i++; break;
        case "--class" when next is not null: className = next; i++; break;
        case "--access" when next is not null: access = next; i++; break;
        case "--levels" when next is not null:
            levels = int.Parse(next, CultureInfo.InvariantCulture);
            i++;
            break;
        case "--sizes" when next is not null:
            sizes = [.. next.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Select(s => int.Parse(s, CultureInfo.InvariantCulture))];
            i++;
            break;
        case "--glyph" when next is not null:
            {
                var parts = next.Split('=', 2);
                if (parts.Length != 2)
                {
                    Console.Error.WriteLine($"bake-icons: --glyph wants Name=U+XXXX, got '{next}'");
                    return 2;
                }
                // U+XXXX, 0xXXXX and bare hex all mean the same. A bare DECIMAL codepoint is deliberately
                // not accepted: it would be ambiguous with hex and silently bake the wrong glyph.
                var raw = parts[1].Trim();
                if (raw.StartsWith("U+", StringComparison.OrdinalIgnoreCase)
                    || raw.StartsWith("0x", StringComparison.OrdinalIgnoreCase))
                {
                    raw = raw[2..];
                }
                if (!int.TryParse(raw, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out var cp))
                {
                    Console.Error.WriteLine($"bake-icons: '{parts[1]}' is not a hex codepoint");
                    return 2;
                }
                icons.Add((parts[0].Trim(), cp));
                i++;
                break;
            }
        default:
            Console.Error.WriteLine($"bake-icons: unknown argument '{args[i]}'");
            return 2;
    }
}

if (fontPath.Length == 0 || outputPath.Length == 0 || ns.Length == 0 || icons.Count == 0)
{
    Console.Error.WriteLine(
        "usage: bake-icons --font <path> --out <file.g.cs> --namespace <ns> --glyph Name=U+XXXX ...");
    return 2;
}

if (!File.Exists(fontPath))
{
    Console.Error.WriteLine($"bake-icons: source font not found: {fontPath}");
    return 2;
}

// LICENSING cannot be checked here, so it is stated where whoever adds a glyph will read it: baking
// redistributes GLYPH SHAPES. Point this at a face whose licence permits that (Noto is OFL). A
// proprietary system face is not a valid source, and a runtime emoji probe legitimately falling back to
// one does not make its outlines redistributable.

using var rasterizer = new ManagedFontRasterizer();
var sb = new StringBuilder();

sb.AppendLine("// <auto-generated>");
sb.AppendLine("//     Generated by bake-icons. Do not edit by hand: re-run the tool and commit.");
sb.AppendLine($"//     Source font: {Path.GetFileName(fontPath)}");
sb.AppendLine("// </auto-generated>");
sb.AppendLine("#nullable enable");
sb.AppendLine();
sb.AppendLine("using System.Collections.Immutable;");
sb.AppendLine("using DIR.Lib;");
sb.AppendLine();
sb.AppendLine($"namespace {ns}");
sb.AppendLine("{");
sb.AppendLine("    /// <summary>Glyph coverage baked at build time, drawn via PixelWidgetBase.DrawCoverageMask.</summary>");
sb.AppendLine("    /// <remarks>");
sb.AppendLine("    /// Baked because a mark drawn from a font at runtime is absent where the face is not installed,");
sb.AppendLine("    /// cannot be tinted when the face is colour, and varies with whichever face the host resolved.");
sb.AppendLine("    /// See <see cref=\"IconBaker\"/>, which also bakes at RUNTIME for marks not known ahead of time.");
sb.AppendLine("    /// </remarks>");
sb.AppendLine($"    {access} static class {className}");
sb.AppendLine("    {");

var total = 0;

foreach (var (name, codepoint) in icons)
{
    var masks = IconBaker.Bake(rasterizer, fontPath, new System.Text.Rune(codepoint), sizes, levels);

    if (masks.Any(m => m.IsEmpty))
    {
        var missing = string.Join(", ", masks.Where(m => m.IsEmpty).Select(m => $"{m.Size}px"));
        Console.Error.WriteLine(
            $"bake-icons: {name} (U+{codepoint:X4}) produced NO coverage at {missing} from " +
            $"{Path.GetFileName(fontPath)}. The face probably does not carry it.");
        return 1;
    }

    sb.AppendLine($"        /// <summary>U+{codepoint:X4}, baked from {Path.GetFileName(fontPath)}.</summary>");
    sb.AppendLine($"        {access} static readonly ImmutableArray<IconBaker.CoverageMask> {name} =");
    sb.AppendLine("        [");
    foreach (var mask in masks)
    {
        sb.Append(CultureInfo.InvariantCulture, $"            new IconBaker.CoverageMask({mask.Size}, [");
        for (var i = 0; i < mask.Runs.Length; i++)
        {
            var r = mask.Runs[i];
            sb.Append(CultureInfo.InvariantCulture, $"new({r.X},{r.Y},{r.Width},{r.Alpha})");
            if (i < mask.Runs.Length - 1)
            {
                sb.Append(", ");
            }
        }
        sb.AppendLine("]),");
        total += mask.Runs.Length;
    }
    sb.AppendLine("        ];");
    sb.AppendLine();

    Console.WriteLine($"bake-icons: {name} U+{codepoint:X4} -> " +
        string.Join(", ", masks.Select(m => $"{m.Size}px:{m.Runs.Length}")));
}

sb.AppendLine("    }");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);
File.WriteAllText(outputPath, sb.ToString().ReplaceLineEndings("\r\n"));

Console.WriteLine($"bake-icons: wrote {outputPath} ({total} runs)");
return 0;
