// <auto-generated>
//     Generated by bake-icons. Do not edit by hand: re-run the tool and commit.
//     Source font: DejaVuSans.ttf
// </auto-generated>
#nullable enable

using System.Collections.Immutable;
using DIR.Lib;

namespace TianWen.UI.Abstractions
{
    /// <summary>Glyph coverage baked at build time, drawn via PixelWidgetBase.DrawCoverageMask.</summary>
    /// <remarks>
    /// Baked because a mark drawn from a font at runtime is absent where the face is not installed,
    /// cannot be tinted when the face is colour, and varies with whichever face the host resolved.
    /// See <see cref="IconBaker"/>, which also bakes at RUNTIME for marks not known ahead of time.
    /// </remarks>
    internal static class SkyIcons
    {
        /// <summary>U+2605, baked from DejaVuSans.ttf.</summary>
        internal static readonly ImmutableArray<IconBaker.CoverageMask> Star5 =
        [
            new IconBaker.CoverageMask(2, [new(0,0,1,63)]),
            new IconBaker.CoverageMask(3, [new(0,0,1,63), new(0,1,2,127)]),
            new IconBaker.CoverageMask(4, [new(1,0,2,63), new(0,1,1,63), new(1,1,1,255), new(2,1,1,191), new(3,1,1,63), new(0,2,1,63), new(1,2,1,191), new(2,2,1,127)]),
            new IconBaker.CoverageMask(5, [new(2,0,1,63), new(0,1,1,63), new(1,1,1,127), new(2,1,1,191), new(3,1,1,127), new(0,2,1,63), new(1,2,1,191), new(2,2,1,255), new(3,2,1,127), new(1,3,2,127), new(3,3,1,63)]),
            new IconBaker.CoverageMask(6, [new(2,0,1,63), new(2,1,1,191), new(3,1,1,63), new(0,2,1,63), new(1,2,1,191), new(2,2,2,255), new(4,2,1,127), new(1,3,1,127), new(2,3,1,255), new(3,3,1,191), new(1,4,1,127), new(2,4,1,63), new(3,4,1,191), new(4,4,1,63)]),
            new IconBaker.CoverageMask(7, [new(2,1,1,63), new(3,1,1,127), new(0,2,1,63), new(1,2,1,127), new(2,2,2,191), new(4,2,1,127), new(5,2,1,63), new(0,3,1,63), new(1,3,1,191), new(2,3,3,255), new(5,3,1,63), new(1,4,1,63), new(2,4,2,255), new(4,4,1,127), new(1,5,2,127), new(3,5,1,63), new(4,5,1,127)]),
            new IconBaker.CoverageMask(8, [new(3,0,1,63), new(3,1,1,255), new(4,1,1,63), new(0,2,1,63), new(1,2,1,127), new(2,2,1,191), new(3,2,1,255), new(4,2,2,191), new(6,2,1,63), new(1,3,1,63), new(2,3,3,255), new(5,3,1,127), new(2,4,3,255), new(5,4,1,63), new(1,5,1,63), new(2,5,1,127), new(4,5,1,127), new(5,5,1,63)]),
            new IconBaker.CoverageMask(9, [new(3,0,2,63), new(3,1,2,127), new(3,2,2,191), new(0,3,1,63), new(1,3,1,191), new(2,3,4,255), new(6,3,1,191), new(7,3,1,63), new(2,4,1,191), new(3,4,2,255), new(5,4,1,191), new(2,5,1,191), new(3,5,2,255), new(5,5,1,191), new(1,6,1,63), new(2,6,1,191), new(3,6,2,63), new(5,6,1,191), new(6,6,1,63)]),
            new IconBaker.CoverageMask(10, [new(4,0,1,63), new(4,1,1,127), new(3,2,1,63), new(4,2,1,255), new(5,2,1,63), new(0,3,1,63), new(1,3,1,127), new(2,3,2,191), new(4,3,1,255), new(5,3,2,191), new(7,3,1,127), new(8,3,1,63), new(1,4,1,63), new(2,4,5,255), new(7,4,1,63), new(2,5,1,63), new(3,5,3,255), new(6,5,1,63), new(2,6,1,127), new(3,6,1,255), new(4,6,1,191), new(5,6,1,255), new(6,6,1,127), new(2,7,1,127), new(3,7,1,63), new(5,7,1,63), new(6,7,1,127)]),
            new IconBaker.CoverageMask(11, [new(4,1,2,63), new(4,2,1,191), new(5,2,1,127), new(4,3,1,255), new(5,3,1,191), new(0,4,1,63), new(1,4,1,191), new(2,4,6,255), new(8,4,1,191), new(9,4,1,63), new(2,5,1,127), new(3,5,4,255), new(7,5,1,127), new(3,6,3,255), new(6,6,1,191), new(2,7,1,63), new(3,7,1,255), new(4,7,1,127), new(5,7,1,191), new(6,7,1,255), new(7,7,1,63), new(2,8,1,127), new(3,8,1,63), new(6,8,2,127)]),
            new IconBaker.CoverageMask(12, [new(6,1,1,63), new(5,2,1,63), new(6,2,1,191), new(5,3,1,127), new(6,3,1,255), new(7,3,1,63), new(2,4,1,63), new(3,4,2,127), new(5,4,1,191), new(6,4,1,255), new(7,4,1,191), new(8,4,2,127), new(10,4,1,63), new(2,5,1,63), new(3,5,6,255), new(9,5,1,191), new(10,5,1,63), new(3,6,1,63), new(4,6,1,191), new(5,6,3,255), new(8,6,1,191), new(4,7,1,191), new(5,7,3,255), new(8,7,1,127), new(3,8,1,63), new(4,8,1,255), new(5,8,1,191), new(6,8,1,63), new(7,8,1,255), new(8,8,1,191), new(3,9,1,63), new(4,9,1,127), new(7,9,1,63), new(8,9,1,191), new(9,9,1,63)]),
            new IconBaker.CoverageMask(14, [new(6,2,1,63), new(7,2,1,127), new(6,3,1,127), new(7,3,1,255), new(6,4,1,191), new(7,4,1,255), new(8,4,1,63), new(2,5,1,63), new(3,5,3,127), new(6,5,2,255), new(8,5,1,191), new(9,5,3,127), new(12,5,1,63), new(2,6,1,63), new(3,6,8,255), new(11,6,1,191), new(12,6,1,63), new(3,7,1,63), new(4,7,1,191), new(5,7,5,255), new(10,7,1,127), new(4,8,1,63), new(5,8,4,255), new(9,8,1,127), new(4,9,1,63), new(5,9,5,255), new(4,10,1,191), new(5,10,1,255), new(6,10,2,63), new(8,10,1,191), new(9,10,1,255), new(10,10,1,63), new(4,11,1,191), new(5,11,1,63), new(9,11,2,127)]),
            new IconBaker.CoverageMask(16, [new(7,1,1,63), new(6,2,1,63), new(7,2,1,191), new(6,3,1,191), new(7,3,1,255), new(6,4,2,255), new(8,4,1,63), new(1,5,1,63), new(2,5,4,127), new(6,5,2,255), new(8,5,1,191), new(9,5,4,127), new(13,5,1,63), new(1,6,1,63), new(2,6,10,255), new(12,6,1,127), new(2,7,1,63), new(3,7,1,191), new(4,7,7,255), new(11,7,1,63), new(4,8,1,127), new(5,8,5,255), new(10,8,1,63), new(4,9,1,127), new(5,9,5,255), new(4,10,3,255), new(7,10,1,191), new(8,10,2,255), new(10,10,1,63), new(3,11,1,63), new(4,11,1,255), new(5,11,1,191), new(6,11,1,63), new(8,11,1,127), new(9,11,1,255), new(10,11,1,127), new(3,12,2,127), new(9,12,1,63), new(10,12,1,191)]),
            new IconBaker.CoverageMask(20, [new(9,2,2,63), new(9,3,2,127), new(9,4,2,191), new(8,5,1,63), new(9,5,2,255), new(11,5,1,63), new(8,6,1,127), new(9,6,2,255), new(11,6,1,127), new(8,7,1,191), new(9,7,2,255), new(11,7,1,191), new(2,8,1,63), new(3,8,14,255), new(17,8,1,63), new(3,9,1,63), new(4,9,1,191), new(5,9,10,255), new(15,9,1,191), new(16,9,1,63), new(5,10,1,127), new(6,10,8,255), new(14,10,1,127), new(6,11,1,63), new(7,11,6,255), new(13,11,1,63), new(6,12,1,127), new(7,12,6,255), new(13,12,1,63), new(6,13,1,191), new(7,13,6,255), new(13,13,1,191), new(5,14,1,63), new(6,14,2,255), new(8,14,1,191), new(9,14,2,63), new(11,14,3,255), new(5,15,1,127), new(6,15,1,255), new(7,15,1,127), new(11,15,1,63), new(12,15,1,127), new(13,15,1,255), new(14,15,1,63), new(5,16,1,127), new(6,16,1,63), new(13,16,1,63), new(14,16,1,127)]),
        ];

    }
}
