using Microsoft.Extensions.Logging;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using TianWen.Lib.Connections;
using TianWen.Lib.Imaging;

namespace TianWen.Lib.Devices;

internal sealed class External(
    IUtf8TextBasedConnectionFactory textBasedConnectionFactory,
    ILogger<External> logger,
    Astrometry.Catalogs.ICelestialObjectDB celestialObjectDB
) : IExternal, IDisposable
{
    private Task? _dbInitTask;
    private readonly SemaphoreSlim _serialPortEnumerationSemaphore = new SemaphoreSlim(1, 1);
    private readonly ConcurrentDictionary<string, ISerialConnection> _serialConnections = [];
    private bool _disposed;

    /// <summary>
    /// Gets the directory where application output files are stored.
    /// </summary>
    /// <remarks>This property provides a convenient location for saving output files generated by the
    /// application. The directory is created if it does not already exist.</remarks>
    public DirectoryInfo AppDataFolder => SharedStaticData.CommonDataRoot;

    public DirectoryInfo ImageOutputFolder { get; } = Directory.CreateDirectory(
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyPictures), SharedStaticData.AppName));

    /// <summary>
    /// Profiles are shared between every consumer of this library, for ease of use
    /// </summary>
    public DirectoryInfo ProfileFolder { get; } = SharedStaticData.CommonDataRoot.CreateSubdirectory("Profiles");

    public async ValueTask<Astrometry.Catalogs.ICelestialObjectDB> GetCelestialObjectDBAsync(CancellationToken cancellationToken = default)
    {
        // Double-checked lazy init: InitDBAsync is idempotent but expensive
        if (_dbInitTask is null or { IsCompleted: false })
        {
            _dbInitTask ??= celestialObjectDB.InitDBAsync(cancellationToken: cancellationToken);
            await _dbInitTask;
        }
        return celestialObjectDB;
    }

    public IReadOnlyList<string> EnumerateAvailableSerialPorts(ResourceLock resourceLock)
    {
        var existingPorts = SerialConnection.EnumerateSerialPorts();

        var availablePorts = new List<string>(existingPorts.Count);

        foreach (var port in existingPorts)
        {
            if (!_serialConnections.TryGetValue(port, out var connection) || !connection.IsOpen)
            {
                availablePorts.Add(port);
            }
        }

        return availablePorts;
    }

    public ValueTask<ResourceLock> WaitForSerialPortEnumerationAsync(CancellationToken cancellationToken) => _serialPortEnumerationSemaphore.AcquireLockAsync(cancellationToken);

    public async ValueTask<ISerialConnection> OpenSerialDeviceAsync(string address, int baud, Encoding encoding, bool assertControlLines = false, CancellationToken cancellationToken = default)
    {
        // BCL SerialPort.Open is a synchronous blocking call (opens the OS handle,
        // queries the line state, etc.): no real async equivalent exists. Offload
        // to the thread pool so callers never block a driver thread on a COM port
        // that takes 10–100 ms (or worse, a stuck USB bridge) to open.
        return await Task.Run(
            () => _serialConnections.AddOrUpdate(address,
                OpenSerialConnection,
                (portName, existing) => existing.IsOpen ? existing : OpenSerialConnection(portName)
            ),
            cancellationToken);

        // assertControlLines asserts DTR + RTS on open (needed by some USB-serial bridges, e.g. the
        // Gemini FlatPanel's CH341). Default false preserves the existing behaviour for every other device.
        ISerialConnection OpenSerialConnection(string portName) => new SerialConnection(portName, baud, encoding, logger, assertControlLines);
    }

    public Task<IUtf8TextBasedConnection> ConnectGuiderAsync(EndPoint address, CommunicationProtocol protocol = CommunicationProtocol.JsonRPC, CancellationToken cancellationToken = default)
        => textBasedConnectionFactory.ConnectAsync(address, protocol, cancellationToken);

    public async ValueTask WriteFitsFileAsync(Image image, string fileName)
    {
        await Task.Run(() => image.WriteToFitsFile(fileName)).ConfigureAwait(false);
    }

    /// <remarks>
    /// Everything held here is a managed wrapper: the semaphore, and serial connections that each own
    /// and release their own OS handle. So there is nothing unmanaged to free and no finalizer.
    /// </remarks>
    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }

        _serialPortEnumerationSemaphore.Dispose();

        foreach (var serialConnection in _serialConnections.Values)
        {
            serialConnection.Dispose();
        }

        _disposed = true;
    }
}
