using Microsoft.Extensions.Logging;
using SharpAstro.Serial;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using TianWen.Lib.Connections;
using TianWen.Lib.Imaging;

namespace TianWen.Lib.Devices;

internal sealed class External(
    IUtf8TextBasedConnectionFactory textBasedConnectionFactory,
    ILogger<External> logger,
    Astrometry.Catalogs.ICelestialObjectDB celestialObjectDB
) : IExternal, IDisposable, IAsyncDisposable
{
    private Task? _dbInitTask;
    private readonly SemaphoreSlim _serialPortEnumerationSemaphore = new SemaphoreSlim(1, 1);
    private readonly ConcurrentDictionary<string, ISerialConnection> _serialConnections = [];

    // Why a port the latest enumeration listed is not to be probed (SerialProbeExclusion), keyed as that list names it.
    private readonly ConcurrentDictionary<string, string> _serialPortsNotToProbe = new(StringComparer.OrdinalIgnoreCase);
    private bool _disposed;

    /// <summary>
    /// Gets the directory where application output files are stored.
    /// </summary>
    /// <remarks>This property provides a convenient location for saving output files generated by the
    /// application. The directory is created if it does not already exist.</remarks>
    public DirectoryInfo AppDataFolder => SharedStaticData.CommonDataRoot;

    public DirectoryInfo ImageOutputFolder { get; } = Directory.CreateDirectory(SpecialFolderHelper.ResolveAppSubFolder(
        Environment.GetFolderPath, Environment.SpecialFolder.MyPictures, SharedStaticData.AppName,
        fallback: Path.Combine(SharedStaticData.CommonDataRoot.FullName, "Images")));

    /// <summary>
    /// Profiles are shared between every consumer of this library, for ease of use
    /// </summary>
    public DirectoryInfo ProfileFolder { get; } = SharedStaticData.CommonDataRoot.CreateSubdirectory("Profiles");

    public async ValueTask<Astrometry.Catalogs.ICelestialObjectDB> GetCelestialObjectDBAsync(CancellationToken cancellationToken = default)
    {
        // Double-checked lazy init: InitDBAsync is idempotent but expensive
        if (_dbInitTask is null or { IsCompleted: false })
        {
            _dbInitTask ??= celestialObjectDB.InitDBAsync(cancellationToken: cancellationToken);
            await _dbInitTask;
        }
        return celestialObjectDB;
    }

    public IReadOnlyList<string> EnumerateAvailableSerialPorts(ResourceLock resourceLock)
    {
        var described = SerialPorts.Enumerate();

        var availablePorts = new List<string>(described.Count);

        foreach (var info in described)
        {
            var port = $"{ISerialConnection.SerialProto}{info.PortName}";
            if (!_serialConnections.TryGetValue(port, out var connection) || !connection.IsOpen)
            {
                availablePorts.Add(port);
            }

            // Per port, as of this enumeration: a COM name can come back with another device behind it.
            if (Discovery.SerialProbeExclusion.ReasonNotToProbe(info) is { } reason)
            {
                _serialPortsNotToProbe[port] = reason;
            }
            else
            {
                _serialPortsNotToProbe.TryRemove(port, out _);
            }
        }

        return availablePorts;
    }

    public string? ReasonNotToProbeSerialPort(string port) => _serialPortsNotToProbe.GetValueOrDefault(port);

    public ValueTask<ResourceLock> WaitForSerialPortEnumerationAsync(CancellationToken cancellationToken) => _serialPortEnumerationSemaphore.AcquireLockAsync(cancellationToken);

    public async ValueTask<ISerialConnection> OpenSerialDeviceAsync(string address, int baud, Encoding encoding, bool assertControlLines = false, CancellationToken cancellationToken = default)
    {
        // A port already open here is handed out again rather than opened twice (the second open would find it busy).
        if (_serialConnections.TryGetValue(address, out var existing) && existing.IsOpen)
        {
            return existing;
        }

        // Serial.Lib bounds the open (a stuck USB bridge, or a Bluetooth port connecting to its remote end, cannot hold
        // the caller) and throws a SerialException naming what went wrong: missing, busy, or not opened in time.
        // assertControlLines asserts DTR + RTS on open (needed by some USB-serial bridges, e.g. the Gemini FlatPanel's
        // CH341); false keeps every other device's open as it was.
        var connection = await SerialConnection.OpenAsync(address, baud, encoding, logger, assertControlLines, cancellationToken).ConfigureAwait(false);
        _serialConnections[address] = connection;
        return connection;
    }

    public Task<IUtf8TextBasedConnection> ConnectGuiderAsync(EndPoint address, CommunicationProtocol protocol = CommunicationProtocol.JsonRPC, CancellationToken cancellationToken = default)
        => textBasedConnectionFactory.ConnectAsync(address, protocol, cancellationToken);

    public async ValueTask WriteFitsFileAsync(Image image, string fileName)
    {
        await Task.Run(() => image.WriteToFitsFile(fileName)).ConfigureAwait(false);
    }

    /// <remarks>
    /// Everything held here is a managed wrapper: the semaphore, and serial connections that each own
    /// and release their own OS handle. So there is nothing unmanaged to free and no finalizer.
    /// </remarks>
    public async ValueTask DisposeAsync()
    {
        if (_disposed)
        {
            return;
        }
        _disposed = true;
        _serialPortEnumerationSemaphore.Dispose();

        foreach (var serialConnection in _serialConnections.Values)
        {
            await serialConnection.DisposeAsync().ConfigureAwait(false);
        }
    }

    /// <summary>
    /// For a container disposed synchronously: each connection's close is started and left to finish on its own
    /// (bounded by the transport), never waited on. <see cref="DisposeAsync"/> is the path that waits.
    /// </summary>
    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }
        _disposed = true;
        _serialPortEnumerationSemaphore.Dispose();

        foreach (var serialConnection in _serialConnections.Values)
        {
            serialConnection.CloseInBackground(logger);
        }
    }
}
