using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Text.Json;
using TianWen.Lib.Imaging.Deconvolution;
using TianWen.Lib.Imaging.Degradation;
using Xunit;

namespace TianWen.Lib.Tests;

/// <summary>
/// Writes the fixture <c>training/denoise/n2n_rl_parity.py</c> pins the torch Richardson-Lucy operator
/// against: a synthetic star field, its blur by a known Moffat, and THIS implementation's estimate at a
/// fixed iteration count, as raw little-endian float32 planes plus a JSON sidecar naming the
/// parameters.
/// </summary>
/// <remarks>
/// <para>The E3 operator (<c>n2n_operator.rl_deconvolve</c>) is a port of <see cref="RichardsonLucy"/>
/// and of <see cref="PsfKernel"/>'s Moffat, and a port that is quietly off (a flipped kernel, a
/// zero-padded border where the C# clamps, a different denominator floor) still deconvolves
/// something and passes every gate that does not know the answer. The oracle ceiling every arm is
/// read against was measured with the C# iteration, so the torch iteration has to be the SAME
/// operator to a rounding tolerance, and the only way to know is to run both on one input and
/// subtract.</para>
/// <para>Opt-in through <c>TIANWEN_RL_FIXTURE_DIR</c> (skips otherwise), because it writes files and a
/// unit run should not. Deterministic: a fixed seed for the star positions and the noise, so the
/// fixture can be regenerated byte-identical after either side changes.</para>
/// </remarks>
public sealed class RichardsonLucyPortFixtureProbe
{
    private const string DirVar = "TIANWEN_RL_FIXTURE_DIR";
    private const int Size = 128;
    private const int Iterations = 20;
    private const double TruthFwhm = 2.4;
    private const double TruthBeta = 3.0;
    private const double BlurFwhm = 3.6;
    private const double BlurBeta = 4.5;
    private const float Background = 0.05f;
    private const float NoiseSigma = 0.002f;

    [Fact]
    public void WriteTheFixtureTheTorchPortIsPinnedAgainst()
    {
        var dir = Environment.GetEnvironmentVariable(DirVar);
        Assert.SkipWhen(string.IsNullOrWhiteSpace(dir), $"{DirVar} not set");
        Directory.CreateDirectory(dir!);

        // Forty point sources on a flat background, made into stars by a narrow Moffat, so the
        // truth has the profile the gate measures widths on rather than a delta the kernel alone shapes.
        var rng = new Random(20260913);
        var deltas = new float[Size * Size];
        Array.Fill(deltas, Background);
        for (var i = 0; i < 40; i++)
        {
            var x = rng.Next(8, Size - 8);
            var y = rng.Next(8, Size - 8);
            deltas[(y * Size) + x] += 0.2f + (0.8f * (float)rng.NextDouble());
        }
        var truth = PsfKernel.Moffat(TruthFwhm, TruthBeta).Convolve(deltas, Size, Size);

        var blur = PsfKernel.Moffat(BlurFwhm, BlurBeta);
        var observed = blur.Convolve(truth, Size, Size);
        // Gaussian read noise, Box-Muller off the same seeded stream, so the fixture is noisy the way
        // a degraded tile is and the iteration has something to fit besides the blur.
        for (var i = 0; i < observed.Length; i += 2)
        {
            var u1 = 1.0 - rng.NextDouble();
            var u2 = rng.NextDouble();
            var mag = Math.Sqrt(-2.0 * Math.Log(u1));
            observed[i] += (float)(mag * Math.Cos(2.0 * Math.PI * u2)) * NoiseSigma;
            if (i + 1 < observed.Length)
            {
                observed[i + 1] += (float)(mag * Math.Sin(2.0 * Math.PI * u2)) * NoiseSigma;
            }
        }

        var result = RichardsonLucy.Deconvolve(observed, Size, Size, blur, Iterations);

        WritePlane(Path.Combine(dir!, "truth.f32"), truth);
        WritePlane(Path.Combine(dir!, "observed.f32"), observed);
        WritePlane(Path.Combine(dir!, "estimate.f32"), result.Estimate);
        WritePlane(Path.Combine(dir!, "kernel.f32"), blur.Weights.ToArray());
        File.WriteAllText(Path.Combine(dir!, "fixture.json"), JsonSerializer.Serialize(new
        {
            size = Size,
            iterations = Iterations,
            blurFwhm = BlurFwhm,
            blurBeta = BlurBeta,
            kernelRadius = blur.Radius,
            kernelSize = blur.Size,
            truthFwhm = TruthFwhm,
            truthBeta = TruthBeta,
            clampedFraction = result.ClampedFraction,
            layout = "row-major float32 little-endian, kernel row-major (kernelSize x kernelSize)",
        }));

        Assert.Equal(Iterations, result.Iterations);
        Assert.Equal(0.0, result.ClampedFraction, 3);
    }

    private static void WritePlane(string path, float[] values)
        => File.WriteAllBytes(path, MemoryMarshal.AsBytes<float>(values).ToArray());
}
