using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;
using static Astap.Lib.EnumHelper;

namespace Astap.Lib.Astrometry
{
    public enum Constellation : ulong
    {
        Andromeda = 'A' << 16 | 'n' << 8 | 'd',
        Antlia = 'A' << 16 | 'n' << 8 | 't',
        Apus = 'A' << 16 | 'p' << 8 | 's',
        Aquarius = 'A' << 16 | 'q' << 8 | 'r',
        Aquila = 'A' << 16 | 'q' << 8 | 'l',
        Ara = 'A' << 16 | 'r' << 8 | 'a',
        Aries = 'A' << 16 | 'r' << 8 | 'i',
        Auriga = 'A' << 16 | 'u' << 8 | 'r',
        Bootes = 'B' << 16 | 'o' << 8 | 'o',
        Caelum = 'C' << 16 | 'a' << 8 | 'e',
        Camelopardalis = 'C' << 16 | 'a' << 8 | 'm',
        Cancer = 'C' << 16 | 'n' << 8 | 'c',
        CanesVenatici = 'C' << 16 | 'V' << 8 | 'n',
        CanisMajor = 'C' << 16 | 'M' << 8 | 'a',
        CanisMinor = 'C' << 16 | 'M' << 8 | 'i',
        Capricornus = 'C' << 16 | 'a' << 8 | 'p',
        Carina = 'C' << 16 | 'a' << 8 | 'r',
        Cassiopeia = 'C' << 16 | 'a' << 8 | 's',
        Cepheus = 'C' << 16 | 'e' << 8 | 'p',
        Cetus = 'C' << 16 | 'e' << 8 | 't',
        Chamaeleon = 'C' << 16 | 'h' << 8 | 'a',
        Circinus = 'C' << 16 | 'i' << 8 | 'r',
        Columba = 'C' << 16 | 'o' << 8 | 'l',
        ComaBerenices = 'C' << 16 | 'o' << 8 | 'm',
        CoronaAustralis = 'C' << 16 | 'r' << 8 | 'A',
        CoronaBorealis = 'C' << 16 | 'r' << 8 | 'B',
        Corvus = 'C' << 16 | 'r' << 8 | 'v',
        Crater = 'C' << 16 | 'r' << 8 | 't',
        Crux = 'C' << 16 | 'r' << 8 | 'u',
        Cygnus = 'C' << 16 | 'y' << 8 | 'g',
        Delphinus = 'D' << 16 | 'e' << 8 | 'l',
        Dorado = 'D' << 16 | 'o' << 8 | 'r',
        Draco = 'D' << 16 | 'r' << 8 | 'a',
        Equuleus = 'E' << 16 | 'q' << 8 | 'u',
        Eridanus = 'E' << 16 | 'r' << 8 | 'i',
        Fornax = 'F' << 16 | 'o' << 8 | 'r',
        Gemini = 'G' << 16 | 'e' << 8 | 'm',
        Grus = 'G' << 16 | 'r' << 8 | 'u',
        Hercules = 'H' << 16 | 'e' << 8 | 'r',
        Horologium = 'H' << 16 | 'o' << 8 | 'r',
        Hydra = 'H' << 16 | 'y' << 8 | 'a',
        Hydrus = 'H' << 16 | 'y' << 8 | 'i',
        Indus = 'I' << 16 | 'n' << 8 | 'd',
        Lacerta = 'L' << 16 | 'a' << 8 | 'c',
        Leo = 'L' << 16 | 'e' << 8 | 'o',
        LeoMinor = 'L' << 16 | 'M' << 8 | 'i',
        Lepus = 'L' << 16 | 'e' << 8 | 'p',
        Libra = 'L' << 16 | 'i' << 8 | 'b',
        Lupus = 'L' << 16 | 'u' << 8 | 'p',
        Lynx = 'L' << 16 | 'y' << 8 | 'x',
        Lyra = 'L' << 16 | 'y' << 8 | 'r',
        Mensa = 'M' << 16 | 'e' << 8 | 'n',
        Microscopium = 'M' << 16 | 'i' << 8 | 'c',
        Monoceros = 'M' << 16 | 'o' << 8 | 'n',
        Musca = 'M' << 16 | 'u' << 8 | 's',
        Norma = 'N' << 16 | 'o' << 8 | 'r',
        Octans = 'O' << 16 | 'c' << 8 | 't',
        Ophiuchus = 'O' << 16 | 'p' << 8 | 'h',
        Orion = 'O' << 16 | 'r' << 8 | 'i',
        Pavo = 'P' << 16 | 'a' << 8 | 'v',
        Pegasus = 'P' << 16 | 'e' << 8 | 'g',
        Perseus = 'P' << 16 | 'e' << 8 | 'r',
        Phoenix = 'P' << 16 | 'h' << 8 | 'e',
        Pictor = 'P' << 16 | 'i' << 8 | 'c',
        Pisces = 'P' << 16 | 's' << 8 | 'c',
        PiscisAustrinus = 'P' << 16 | 's' << 8 | 'a',
        Puppis = 'P' << 16 | 'u' << 8 | 'p',
        Pyxis = 'P' << 16 | 'y' << 8 | 'x',
        Reticulum = 'R' << 16 | 'e' << 8 | 't',
        Sagitta = 'S' << 16 | 'g' << 8 | 'e',
        Sagittarius = 'S' << 16 | 'g' << 8 | 'r',
        Scorpius = 'S' << 16 | 'c' << 8 | 'o',
        Sculptor = 'S' << 16 | 'c' << 8 | 'l',
        Scutum = 'S' << 16 | 'c' << 8 | 't',
        Serpens = 'S' << 16 | 'e' << 8 | 'r',
        SerpensCaput = 'S' << 16 | 'e' << 8 | '1',
        SerpensCauda = 'S' << 16 | 'e' << 8 | '2',
        Sextans = 'S' << 16 | 'e' << 8 | 'x',
        Taurus = 'T' << 16 | 'a' << 8 | 'u',
        Telescopium = 'T' << 16 | 'e' << 8 | 'l',
        Triangulum = 'T' << 16 | 'r' << 8 | 'i',
        TriangulumAustrale = 'T' << 16 | 'r' << 8 | 'A',
        Tucana = 'T' << 16 | 'u' << 8 | 'c',
        UrsaMajor = 'U' << 16 | 'M' << 8 | 'a',
        UrsaMinor = 'U' << 16 | 'M' << 8 | 'i',
        Vela = 'V' << 16 | 'e' << 8 | 'l',
        Virgo = 'V' << 16 | 'i' << 8 | 'r',
        Volans = 'V' << 16 | 'o' << 8 | 'l',
        Vulpecula = 'V' << 16 | 'u' << 8 | 'l'
    }

    public static class ConstellationEx
    {
        private static readonly Dictionary<Constellation, (string Genetitive, string BrightestStar)> _info = new()
        {
            [Constellation.Andromeda] = ("Andromedae", "Alpheratz"),
            [Constellation.Antlia] = ("Antliae", "α Antliae"),
            [Constellation.Apus] = ("Apodis", "α Apodis"),
            [Constellation.Aquarius] = ("Aquarii", "Sadalsuud"),
            [Constellation.Aquila] = ("Aquilae", "Altair"),
            [Constellation.Ara] = ("Arae", "β Arae"),
            [Constellation.Aries] = ("Arietis", "Hamal"),
            [Constellation.Auriga] = ("Aurigae", "Capella"),
            [Constellation.Bootes] = ("Bootis", "Arcturus"),
            [Constellation.Caelum] = ("Caeli", "α Caeli"),
            [Constellation.Camelopardalis] = ("Camelopardalis", "β Camelopardalis"),
            [Constellation.Cancer] = ("Cancri", "Tarf"),
            [Constellation.CanesVenatici] = ("Canum Venaticorum", "Cor Caroli"),
            [Constellation.CanisMajor] = ("Canis Majoris", "Sirius"),
            [Constellation.CanisMinor] = ("Canis Minoris", "Procyon"),
            [Constellation.Capricornus] = ("Capricorni", "Deneb Algedi"),
            [Constellation.Carina] = ("Carinae", "Canopus"),
            [Constellation.Cassiopeia] = ("Cassiopeiae", "Schedar"),
            [Constellation.Cepheus] = ("Centauri", "Rigil Kentaurus"),
            [Constellation.Cetus] = ("Cephei", "Alderamin"),
            [Constellation.Chamaeleon] = ("Ceti", "Diphda"),
            [Constellation.Circinus] = ("Chamaeleontis", "α Chamaeleontis"),
            [Constellation.Columba] = ("Circini", "α Circini"),
            [Constellation.ComaBerenices] = ("Columbae", "Phact"),
            [Constellation.CoronaAustralis] = ("Comae Berenices", "β Comae Berenices"),
            [Constellation.CoronaBorealis] = ("Coronae Borealis", "Alphecca"),
            [Constellation.Corvus] = ("Corvi", "Gienah"),
            [Constellation.Crater] = ("Crateris", "δ Crateris"),
            [Constellation.Crux] = ("Crucis", "Acrux"),
            [Constellation.Cygnus] = ("Cygni", "Deneb"),
            [Constellation.Delphinus] = ("Delphini", "Rotanev"),
            [Constellation.Dorado] = ("Doradus", "α Doradus"),
            [Constellation.Draco] = ("Draconis", "Eltanin"),
            [Constellation.Equuleus] = ("Equulei", "Kitalpha"),
            [Constellation.Eridanus] = ("Eridani", "Achernar"),
            [Constellation.Fornax] = ("Fornacis", "Dalim"),
            [Constellation.Gemini] = ("Geminorum", "Pollux"),
            [Constellation.Grus] = ("Gruis", "Alnair"),
            [Constellation.Hercules] = ("Herculis", "Kornephoros"),
            [Constellation.Horologium] = ("Horologii", "α Horologii"),
            [Constellation.Hydra] = ("Hydrae", "Alphard"),
            [Constellation.Hydrus] = ("Hydri", "β Hydri"),
            [Constellation.Indus] = ("Indi", "α Indi"),
            [Constellation.Lacerta] = ("Lacertae", "α Lacertae"),
            [Constellation.Leo] = ("Leonis", "Regulus"),
            [Constellation.LeoMinor] = ("Leonis Minoris", "Praecipua"),
            [Constellation.Lepus] = ("Leporis", "Arneb"),
            [Constellation.Libra] = ("Librae", "Zubeneschamali"),
            [Constellation.Lupus] = ("Lupi", "α Lupi"),
            [Constellation.Lynx] = ("Lyncis", "α Lyncis"),
            [Constellation.Lyra] = ("Lyrae", "Vega"),
            [Constellation.Mensa] = ("Mensae", "α Mensae"),
            [Constellation.Microscopium] = ("Microscopii", "γ Microscopii"),
            [Constellation.Monoceros] = ("Monocerotis", "β Monocerotis"),
            [Constellation.Musca] = ("Muscae", "α Muscae"),
            [Constellation.Norma] = ("Normae", "γ2 Normae"),
            [Constellation.Octans] = ("Octantis", "ν Octantis"),
            [Constellation.Ophiuchus] = ("Ophiuchi", "Rasalhague"),
            [Constellation.Orion] = ("Orionis", "Rigel"),
            [Constellation.Pavo] = ("Pavonis", "Peacock"),
            [Constellation.Pegasus] = ("Pegasi", "Enif"),
            [Constellation.Perseus] = ("Persei", "Mirfak"),
            [Constellation.Phoenix] = ("Phoenicis", "Ankaa"),
            [Constellation.Pictor] = ("Pictoris", "α Pictoris"),
            [Constellation.Pisces] = ("Piscium", "Alpherg"),
            [Constellation.PiscisAustrinus] = ("Piscis Austrini", "Fomalhaut"),
            [Constellation.Puppis] = ("Puppis", "Naos"),
            [Constellation.Pyxis] = ("Pyxidis", "α Pyxidis"),
            [Constellation.Reticulum] = ("Reticuli", "α Reticuli"),
            [Constellation.Sagitta] = ("Sagittae", "γ Sagittae"),
            [Constellation.Sagittarius] = ("Sagittarii", "Kaus Australis"),
            [Constellation.Scorpius] = ("Scorpii", "Antares"),
            [Constellation.Sculptor] = ("Sculptoris", "α Sculptoris"),
            [Constellation.Scutum] = ("Scuti", "α Scuti"),
            [Constellation.Serpens] = ("Serpentis", "Unukalhai"),
            [Constellation.SerpensCaput] = ("Serpentis", "Unukalhai"),
            [Constellation.SerpensCauda] = ("Serpentis", "η Serpentis"),
            [Constellation.Sextans] = ("Sextantis", "α Sextantis"),
            [Constellation.Taurus] = ("Tauri", "Aldebaran"),
            [Constellation.Telescopium] = ("Telescopii", "α Telescopii"),
            [Constellation.Triangulum] = ("Trianguli", "β Trianguli"),
            [Constellation.TriangulumAustrale] = ("Trianguli Australis", "Atria"),
            [Constellation.Tucana] = ("Tucanae", "α Tucanae"),
            [Constellation.UrsaMajor] = ("Ursae Majoris", "Alioth"),
            [Constellation.UrsaMinor] = ("Ursae Minoris", "Polaris"),
            [Constellation.Vela] = ("Velorum", "γ2 Velorum"),
            [Constellation.Virgo] = ("Virginis", "Spica"),
            [Constellation.Volans] = ("Volantis", "β Volantis"),
            [Constellation.Vulpecula] = ("Vulpeculae", "Anser")
        };

        public static string ToGenitive(this Constellation constellation)
            => _info.TryGetValue(constellation, out var info)
                ? info.Genetitive
                : throw new ArgumentException($"Cannot find genitive for constellation {constellation}", nameof(constellation));

        public static string ToIAUAbbreviation(this Constellation constellation) => EnumValueToAbbreviation((ulong)constellation);

        public static bool IsContainedWithin(this Constellation constellation, Constellation parent)
        {
            if (constellation == parent)
            {
                return true;
            }
            else if (parent == Constellation.Serpens)
            {
                return constellation is Constellation.SerpensCaput or Constellation.SerpensCauda;
            }
            return false;
        }
    }
}