using static Astap.Lib.EnumHelper;

namespace Astap.Lib.Astrometry
{
    public enum Constellation : ulong
    {
        Andromeda = 'A' << 16 | 'n' << 8 | 'd',
        Antlia = 'A' << 16 | 'n' << 8 | 't',
        Apus = 'A' << 16 | 'p' << 8 | 's',
        Aquarius = 'A' << 16 | 'q' << 8 | 'r',
        Aquila = 'A' << 16 | 'q' << 8 | 'l',
        Ara = 'A' << 16 | 'r' << 8 | 'a',
        Aries = 'A' << 16 | 'r' << 8 | 'i',
        Auriga = 'A' << 16 | 'u' << 8 | 'r',
        Bootes = 'B' << 16 | 'o' << 8 | 'o',
        Caelum = 'C' << 16 | 'a' << 8 | 'e',
        Camelopardalis = 'C' << 16 | 'a' << 8 | 'm',
        Cancer = 'C' << 16 | 'n' << 8 | 'c',
        CanesVenatici = 'C' << 16 | 'V' << 8 | 'n',
        CanisMajor = 'C' << 16 | 'M' << 8 | 'a',
        CanisMinor = 'C' << 16 | 'M' << 8 | 'i',
        Capricornus = 'C' << 16 | 'a' << 8 | 'p',
        Carina = 'C' << 16 | 'a' << 8 | 'r',
        Cassiopeia = 'C' << 16 | 'a' << 8 | 's',
        Cepheus = 'C' << 16 | 'e' << 8 | 'p',
        Cetus = 'C' << 16 | 'e' << 8 | 't',
        Chamaeleon = 'C' << 16 | 'h' << 8 | 'a',
        Circinus = 'C' << 16 | 'i' << 8 | 'r',
        Columba = 'C' << 16 | 'o' << 8 | 'l',
        ComaBerenices = 'C' << 16 | 'o' << 8 | 'm',
        CoronaAustralis = 'C' << 16 | 'r' << 8 | 'A',
        CoronaBorealis = 'C' << 16 | 'r' << 8 | 'B',
        Corvus = 'C' << 16 | 'r' << 8 | 'v',
        Crater = 'C' << 16 | 'r' << 8 | 't',
        Crux = 'C' << 16 | 'r' << 8 | 'u',
        Cygnus = 'C' << 16 | 'y' << 8 | 'g',
        Delphinus = 'D' << 16 | 'e' << 8 | 'l',
        Dorado = 'D' << 16 | 'o' << 8 | 'r',
        Draco = 'D' << 16 | 'r' << 8 | 'a',
        Equuleus = 'E' << 16 | 'q' << 8 | 'u',
        Eridanus = 'E' << 16 | 'r' << 8 | 'i',
        Fornax = 'F' << 16 | 'o' << 8 | 'r',
        Gemini = 'G' << 16 | 'e' << 8 | 'm',
        Grus = 'G' << 16 | 'r' << 8 | 'u',
        Hercules = 'H' << 16 | 'e' << 8 | 'r',
        Horologium = 'H' << 16 | 'o' << 8 | 'r',
        Hydra = 'H' << 16 | 'y' << 8 | 'a',
        Hydrus = 'H' << 16 | 'y' << 8 | 'i',
        Indus = 'I' << 16 | 'n' << 8 | 'd',
        Lacerta = 'L' << 16 | 'a' << 8 | 'c',
        Leo = 'L' << 16 | 'e' << 8 | 'o',
        LeoMinor = 'L' << 16 | 'M' << 8 | 'i',
        Lepus = 'L' << 16 | 'e' << 8 | 'p',
        Libra = 'L' << 16 | 'i' << 8 | 'b',
        Lupus = 'L' << 16 | 'u' << 8 | 'p',
        Lynx = 'L' << 16 | 'y' << 8 | 'x',
        Lyra = 'L' << 16 | 'y' << 8 | 'r',
        Mensa = 'M' << 16 | 'e' << 8 | 'n',
        Microscopium = 'M' << 16 | 'i' << 8 | 'c',
        Monoceros = 'M' << 16 | 'o' << 8 | 'n',
        Musca = 'M' << 16 | 'u' << 8 | 's',
        Norma = 'N' << 16 | 'o' << 8 | 'r',
        Octans = 'O' << 16 | 'c' << 8 | 't',
        Ophiuchus = 'O' << 16 | 'p' << 8 | 'h',
        Orion = 'O' << 16 | 'r' << 8 | 'i',
        Pavo = 'P' << 16 | 'a' << 8 | 'v',
        Pegasus = 'P' << 16 | 'e' << 8 | 'g',
        Perseus = 'P' << 16 | 'e' << 8 | 'r',
        Phoenix = 'P' << 16 | 'h' << 8 | 'e',
        Pictor = 'P' << 16 | 'i' << 8 | 'c',
        Pisces = 'P' << 16 | 's' << 8 | 'c',
        PiscisAustrinus = 'P' << 16 | 's' << 8 | 'a',
        Puppis = 'P' << 16 | 'u' << 8 | 'p',
        Pyxis = 'P' << 16 | 'y' << 8 | 'x',
        Reticulum = 'R' << 16 | 'e' << 8 | 't',
        Sagitta = 'S' << 16 | 'g' << 8 | 'e',
        Sagittarius = 'S' << 16 | 'g' << 8 | 'r',
        Scorpius = 'S' << 16 | 'c' << 8 | 'o',
        Sculptor = 'S' << 16 | 'c' << 8 | 'l',
        Scutum = 'S' << 16 | 'c' << 8 | 't',
        Serpens = 'S' << 16 | 'e' << 8 | 'r',
        SerpensCaput = 'S' << 16 | 'e' << 8 | '1',
        SerpensCauda = 'S' << 16 | 'e' << 8 | '2',
        Sextans = 'S' << 16 | 'e' << 8 | 'x',
        Taurus = 'T' << 16 | 'a' << 8 | 'u',
        Telescopium = 'T' << 16 | 'e' << 8 | 'l',
        Triangulum = 'T' << 16 | 'r' << 8 | 'i',
        TriangulumAustrale = 'T' << 16 | 'r' << 8 | 'A',
        Tucana = 'T' << 16 | 'u' << 8 | 'c',
        UrsaMajor = 'U' << 16 | 'M' << 8 | 'a',
        UrsaMinor = 'U' << 16 | 'M' << 8 | 'i',
        Vela = 'V' << 16 | 'e' << 8 | 'l',
        Virgo = 'V' << 16 | 'i' << 8 | 'r',
        Volans = 'V' << 16 | 'o' << 8 | 'l',
        Vulpecula = 'V' << 16 | 'u' << 8 | 'l'
    }

    public static class ConstellationEx
    {
        public static string ToIAUAbbreviation(this Constellation constellation) => EnumValueToAbbreviation((ulong)constellation);
    }
}
