using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace TianWen.Lib.SourceGenerators;

// SymbolDisplayFormat that includes nullable reference type annotations (e.g. string?)
static class DisplayFormats
{
    internal static readonly SymbolDisplayFormat FullyQualifiedWithNullable =
        SymbolDisplayFormat.FullyQualifiedFormat.AddMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);
}

[Generator]
public sealed class DispatchInterfaceGenerator : IIncrementalGenerator
{
    private const string AttributeSource = @"// <auto-generated/>
#nullable enable

namespace TianWen.Lib.Devices.Ascom.ComInterop;

/// <summary>
/// Marks a partial class as an IDispatch COM wrapper.
/// The source generator will implement all partial property and method bodies
/// using AOT-safe IDispatch calls.
/// </summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
internal sealed class DispatchInterfaceAttribute : global::System.Attribute
{
}
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Always emit the attribute
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("DispatchInterfaceAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        // Find all partial classes decorated with [DispatchInterface]
        var classDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "TianWen.Lib.Devices.Ascom.ComInterop.DispatchInterfaceAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax c && c.Modifiers.Any(SyntaxKind.PartialKeyword),
                transform: static (ctx, ct) => GetDispatchClassInfo(ctx, ct))
            .Where(static info => info is not null);

        context.RegisterSourceOutput(classDeclarations, static (spc, classInfo) =>
        {
            if (classInfo is not null)
            {
                var source = GenerateDispatchImplementation(classInfo);
                spc.AddSource($"{classInfo.ClassName}.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static DispatchClassInfo? GetDispatchClassInfo(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol)
            return null;

        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        var properties = new List<DispatchPropertyInfo>();
        var methods = new List<DispatchMethodInfo>();

        foreach (var member in classSymbol.GetMembers())
        {
            ct.ThrowIfCancellationRequested();

            if (member is IPropertySymbol prop && prop.IsPartialDefinition)
            {
                // The COM member name is the same as the C# property name
                var comName = prop.Name;
                properties.Add(new DispatchPropertyInfo(
                    prop.Name,
                    comName,
                    prop.Type.ToDisplayString(DisplayFormats.FullyQualifiedWithNullable),
                    prop.GetMethod is not null,
                    prop.SetMethod is not null));
            }
            else if (member is IMethodSymbol method
                && method.IsPartialDefinition
                && method.MethodKind == MethodKind.Ordinary)
            {
                var comName = method.Name;
                var parameters = method.Parameters.Select(p => new DispatchParameterInfo(
                    p.Name,
                    p.Type.ToDisplayString(DisplayFormats.FullyQualifiedWithNullable))).ToImmutableArray();

                methods.Add(new DispatchMethodInfo(
                    method.Name,
                    comName,
                    method.ReturnsVoid ? null : method.ReturnType.ToDisplayString(DisplayFormats.FullyQualifiedWithNullable),
                    parameters));
            }
        }

        if (properties.Count == 0 && methods.Count == 0)
            return null;

        return new DispatchClassInfo(
            namespaceName,
            classSymbol.Name,
            classSymbol.DeclaredAccessibility,
            properties.ToImmutableArray(),
            methods.ToImmutableArray());
    }

    private static string GenerateDispatchImplementation(DispatchClassInfo classInfo)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (classInfo.Namespace is not null)
        {
            sb.AppendLine($"namespace {classInfo.Namespace};");
            sb.AppendLine();
        }

        var accessibility = classInfo.Accessibility switch
        {
            Accessibility.Internal => "internal",
            Accessibility.Public => "public",
            Accessibility.Private => "private",
            _ => "internal"
        };

        sb.AppendLine($"{accessibility} partial class {classInfo.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::TianWen.Lib.Devices.Ascom.ComInterop.DispatchObject _dispatch;");
        sb.AppendLine();

        // Generate property implementations
        foreach (var prop in classInfo.Properties)
        {
            var getterCall = GetDispatchGetterCall(prop.TypeName, prop.ComName);
            var setterCall = GetDispatchSetterCall(prop.TypeName, prop.ComName);

            sb.AppendLine($"    public partial {prop.TypeName} {prop.Name}");
            sb.AppendLine("    {");
            if (prop.HasGetter)
            {
                sb.AppendLine($"        get => {getterCall};");
            }
            if (prop.HasSetter)
            {
                sb.AppendLine($"        set => {setterCall};");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Generate method implementations
        foreach (var method in classInfo.Methods)
        {
            var returnType = method.ReturnTypeName ?? "void";
            var paramList = string.Join(", ", method.Parameters.Select(p => $"{p.TypeName} {p.Name}"));

            sb.Append($"    public partial {returnType} {method.Name}({paramList})");

            if (method.Parameters.Length == 0 && method.ReturnTypeName is null)
            {
                sb.AppendLine();
                sb.AppendLine($"        => _dispatch.InvokeMethod(\"{method.ComName}\");");
            }
            else if (method.ReturnTypeName is null)
            {
                var args = string.Join(", ", method.Parameters.Select(p => p.Name));
                sb.AppendLine();
                sb.AppendLine($"        => _dispatch.InvokeMethod(\"{method.ComName}\", {args});");
            }
            else
            {
                var call = GetDispatchMethodCall(method.ReturnTypeName, method.ComName, method.Parameters);
                sb.AppendLine();
                sb.AppendLine($"        => {call};");
            }
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetDispatchGetterCall(string typeName, string comName)
    {
        return typeName switch
        {
            "bool" => $"_dispatch.GetBool(\"{comName}\")",
            "int" => $"_dispatch.GetInt(\"{comName}\")",
            "short" => $"_dispatch.GetShort(\"{comName}\")",
            "double" => $"_dispatch.GetDouble(\"{comName}\")",
            "string" or "string?" => $"_dispatch.GetString(\"{comName}\")",
            "global::System.DateTime" => $"_dispatch.GetDateTime(\"{comName}\")",
            "int[,]" => $"_dispatch.GetInt2DArray(\"{comName}\")",
            "string[]" or "string?[]" => $"_dispatch.GetStringArray(\"{comName}\")",
            "int[]" => $"_dispatch.GetIntArray(\"{comName}\")",
            _ => $"({typeName})_dispatch.GetObject(\"{comName}\")"
        };
    }

    private static string GetDispatchSetterCall(string typeName, string comName)
    {
        return $"_dispatch.Set(\"{comName}\", value)";
    }

    private static string GetDispatchMethodCall(string returnTypeName, string comName, ImmutableArray<DispatchParameterInfo> parameters)
    {
        var args = parameters.Length > 0
            ? ", " + string.Join(", ", parameters.Select(p => p.Name))
            : "";

        return returnTypeName switch
        {
            "bool" => $"_dispatch.InvokeMethodBool(\"{comName}\"{args})",
            "int" => $"_dispatch.InvokeMethodInt(\"{comName}\"{args})",
            "double" => $"_dispatch.InvokeMethodDouble(\"{comName}\"{args})",
            _ => $"({returnTypeName})_dispatch.InvokeMethodObject(\"{comName}\"{args})"
        };
    }
}

internal sealed class DispatchClassInfo
{
    public DispatchClassInfo(string? ns, string className, Accessibility accessibility, ImmutableArray<DispatchPropertyInfo> properties, ImmutableArray<DispatchMethodInfo> methods)
    {
        Namespace = ns;
        ClassName = className;
        Accessibility = accessibility;
        Properties = properties;
        Methods = methods;
    }

    public string? Namespace { get; }
    public string ClassName { get; }
    public Accessibility Accessibility { get; }
    public ImmutableArray<DispatchPropertyInfo> Properties { get; }
    public ImmutableArray<DispatchMethodInfo> Methods { get; }
}

internal sealed class DispatchPropertyInfo
{
    public DispatchPropertyInfo(string name, string comName, string typeName, bool hasGetter, bool hasSetter)
    {
        Name = name;
        ComName = comName;
        TypeName = typeName;
        HasGetter = hasGetter;
        HasSetter = hasSetter;
    }

    public string Name { get; }
    public string ComName { get; }
    public string TypeName { get; }
    public bool HasGetter { get; }
    public bool HasSetter { get; }
}

internal sealed class DispatchMethodInfo
{
    public DispatchMethodInfo(string name, string comName, string? returnTypeName, ImmutableArray<DispatchParameterInfo> parameters)
    {
        Name = name;
        ComName = comName;
        ReturnTypeName = returnTypeName;
        Parameters = parameters;
    }

    public string Name { get; }
    public string ComName { get; }
    public string? ReturnTypeName { get; }
    public ImmutableArray<DispatchParameterInfo> Parameters { get; }
}

internal sealed class DispatchParameterInfo
{
    public DispatchParameterInfo(string name, string typeName)
    {
        Name = name;
        TypeName = typeName;
    }

    public string Name { get; }
    public string TypeName { get; }
}
