using System;
using System.Runtime.Versioning;

namespace TianWen.Lib.Devices.Ascom.ComInterop;

/// <summary>
/// AOT-safe dispatch wrapper for an ASCOM Camera COM object.
/// Property/method bodies are generated by the DispatchInterfaceGenerator.
/// </summary>
[SupportedOSPlatform("windows")]
[DispatchInterface]
internal sealed partial class AscomDispatchCamera : IDisposable
{
    public AscomDispatchCamera(DispatchObject dispatch)
    {
        _dispatch = dispatch;
    }

    // Capability properties
    public partial bool CanGetCoolerPower { get; }
    public partial bool CanSetCCDTemperature { get; }
    public partial bool CanStopExposure { get; }
    public partial bool CanAbortExposure { get; }
    public partial bool CanFastReadout { get; }
    public partial bool CanPulseGuide { get; }
    public partial bool CanGetCoolerOn { get; }
    public partial bool CanSetCoolerOn { get; }
    public partial bool CanGetHeatsinkTemperature { get; }
    public partial bool CanGetCCDTemperature { get; }
    public partial bool UsesGainValue { get; }
    public partial bool UsesGainMode { get; }
    public partial bool UsesOffsetValue { get; }
    public partial bool UsesOffsetMode { get; }

    // Read-write properties
    public partial bool CoolerOn { get; set; }
    public partial bool FastReadout { get; set; }
    public partial short BinX { get; set; }
    public partial short BinY { get; set; }
    public partial short Gain { get; set; }
    public partial short ReadoutMode { get; set; }
    public partial int StartX { get; set; }
    public partial int StartY { get; set; }
    public partial int NumX { get; set; }
    public partial int NumY { get; set; }
    public partial int Offset { get; set; }
    public partial double SetCCDTemperature { get; set; }

    // Read-only numeric properties
    public partial short InterfaceVersion { get; }
    public partial short MaxBinX { get; }
    public partial short MaxBinY { get; }
    public partial short GainMin { get; }
    public partial short GainMax { get; }
    public partial int CameraXSize { get; }
    public partial int CameraYSize { get; }
    public partial int MaxADU { get; }
    public partial int OffsetMin { get; }
    public partial int OffsetMax { get; }
    public partial int CameraState { get; }
    public partial int SensorType { get; }
    public partial int BayerOffsetX { get; }
    public partial int BayerOffsetY { get; }
    public partial double PixelSizeX { get; }
    public partial double PixelSizeY { get; }
    public partial double CoolerPower { get; }
    public partial double HeatSinkTemperature { get; }
    public partial double CCDTemperature { get; }
    public partial double FullWellCapacity { get; }
    public partial double ElectronsPerADU { get; }
    public partial double ExposureResolution { get; }
    public partial double LastExposureDuration { get; }
    public partial bool ImageReady { get; }
    public partial bool IsPulseGuiding { get; }

    // Array properties
    public partial string[] Gains { get; }
    public partial string[] Offsets { get; }
    public partial string[] ReadoutModes { get; }
    public partial int[,] ImageArray { get; }

    // Methods
    public partial void StartExposure(double Duration, bool Light);
    public partial void StopExposure();
    public partial void AbortExposure();
    public partial void PulseGuide(int Direction, int Duration);

    public void Dispose() { /* dispatch owned by AscomDispatchDevice */ }
}
