using System;
using System.Runtime.Versioning;

namespace TianWen.Lib.Devices.Ascom.ComInterop;

/// <summary>
/// AOT-safe dispatch wrapper for an ASCOM Telescope COM object.
/// Property/method bodies are generated by the DispatchInterfaceGenerator.
/// </summary>
[SupportedOSPlatform("windows")]
[DispatchInterface]
internal sealed partial class AscomDispatchTelescope : IDisposable
{
    public AscomDispatchTelescope(DispatchObject dispatch)
    {
        _dispatch = dispatch;
    }

    // Capability properties (read-only booleans)
    public partial bool CanSetTracking { get; }
    public partial bool CanSetPierSide { get; }
    public partial bool CanPark { get; }
    public partial bool CanUnpark { get; }
    public partial bool CanSetPark { get; }
    public partial bool CanSlew { get; }
    public partial bool CanSlewAsync { get; }
    public partial bool CanSync { get; }
    public partial bool CanPulseGuide { get; }
    public partial bool CanSetRightAscensionRate { get; }
    public partial bool CanSetDeclinationRate { get; }
    public partial bool CanSetGuideRates { get; }

    // State properties
    public partial bool AtHome { get; }
    public partial bool AtPark { get; }
    public partial bool Slewing { get; }
    public partial bool Tracking { get; set; }
    public partial bool IsPulseGuiding { get; }

    // Coordinate properties
    public partial double RightAscension { get; }
    public partial double Declination { get; }
    public partial double SiderealTime { get; }
    public partial double SiteElevation { get; set; }
    public partial double SiteLatitude { get; set; }
    public partial double SiteLongitude { get; set; }

    // Rate properties
    public partial double RightAscensionRate { get; set; }
    public partial double DeclinationRate { get; set; }
    public partial double GuideRateRightAscension { get; set; }
    public partial double GuideRateDeclination { get; set; }

    // Enum-valued properties (returned as int from COM)
    public partial int EquatorialSystem { get; }
    public partial int AlignmentMode { get; }
    public partial int SideOfPier { get; set; }
    public partial int TrackingRate { get; set; }

    // DateTime property
    public partial DateTime UTCDate { get; set; }

    // Methods
    public partial void Park();
    public partial void Unpark();
    public partial void AbortSlew();
    public partial void SlewToCoordinatesAsync(double RightAscension, double Declination);
    public partial void SyncToCoordinates(double RightAscension, double Declination);
    public partial void PulseGuide(int Direction, int Duration);
    public partial bool CanMoveAxis(int Axis);
    public partial int DestinationSideOfPier(double RightAscension, double Declination);

    public void Dispose() { /* dispatch owned by AscomDispatchDevice */ }
}
