name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  VERSION_PREFIX: 1.3.${{ github.run_number }}
  VERSION_REV: ${{ github.run_attempt }}
  VERSION_SUFFIX: +${{ github.sha }}
  BUILD_CONF: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install astrometry.net
      run: sudo apt-get install -y astrometry.net astrometry-data-2mass-08-19
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build -c $BUILD_CONF --no-restore --version-suffix $VERSION_SUFFIX -p:VersionPrefix=${VERSION_PREFIX}${VERSION_REV} -p:FileVersion=${VERSION_PREFIX}.${VERSION_REV} -p:ContinuousIntegrationBuild=true
      working-directory: src
    - name: Test
      run: dotnet test -c $BUILD_CONF --no-build
      working-directory: src
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nuget-packages
        path: '**/*.nupkg'
        retention-days: 5
  
  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download NuGet packages
      uses: actions/download-artifact@v3
      with:
        name: nuget-packages
    - name: Push NuGet package
      run: dotnet nuget push **/*.nupkg -s nuget.org -k ${{ secrets.NUGET_API_KEY }}
